## Config file
lr:              1e-4 # Initial learning rate
weight_decay:    1e-5
power:           0.9
epochs:          250 # Number of epochs to train the model   
number_classes:  4 # Number of classes in the target dataset
batch_size_tr:   1 # Batch size for train
batch_size_va:   1 # Batch size for validationn 
modalities:      ['flair', 't1', 't1ce', 't2']# List of modalities needd to be used for training and evaluating the model  
path_to_data:    '/home/staff/azad/deeplearning/brats/MICCAI_BraTS_2018_Data_Training/' # path to dataset
path_to_log:     './results/' # path to save results
progress_p:      0.1 # value between 0-1 shows the number of time we need to report training progress in each epoch
validation_p:    0.1 # validation percentage
test_p:          0.2 # Test percentage (20%)
inputshape:      [160, 192, 128] 
weight_mispath:  0.6
weight_content:  0.2